# Generated by Django 5.0.3 on 2024-03-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_request_customer_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cost',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
