# Generated by Django 5.0.3 on 2024-03-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_name_product_p_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
