# Generated by Django 5.0.3 on 2024-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
